---
title: "Using function dispatch"
author: "Nathan Green"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


```{r}
model_transmat <- 
  define_model(transmat =
                 list(probs = matrix(data=c(NA, 0.5, 0.5), nrow = 1),
                      cost = matrix(data=c(NA, 1, 2), nrow = 1)
                 ))
model_transmat

model_tree <- 
  define_model(tree_dat =
                 list(child = list("1" = c(2, 3),
                                   "2" = NULL,
                                   "3" = NULL),
                      dat = data.frame(node = 1:3,
                                       probs = c(NA, 0.5, 0.5),
                                       cost = c(NA, 1, 2))
                 ))
model_tree

model_long <- 
  define_model(dat_long = data.frame(from = c(NA, 1, 1),
                                     to = 1:3,
                                     probs = c(NA, 0.5, 0.5),
                                     cost = c(NA, 1, 2)))
model_long
```


```{r}
dectree_expected_values(model_transmat)
dectree_expected_values(model_tree)
dectree_expected_values(model_long)
```
