// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// Cdectree_expected_values
NumericVector Cdectree_expected_values(NumericMatrix vals, NumericMatrix p);
RcppExport SEXP _CEdecisiontree_Cdectree_expected_values(SEXP valsSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type vals(valsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(Cdectree_expected_values(vals, p));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CEdecisiontree_Cdectree_expected_values", (DL_FUNC) &_CEdecisiontree_Cdectree_expected_values, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_CEdecisiontree(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
