# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Cdectree_expected_values
#'
#' @export
Cdectree_expected_values <- function(vals, p) {
    .Call('_CEdecisiontree_Cdectree_expected_values', PACKAGE = 'CEdecisiontree', vals, p)
}

